version: "3.9"
services:
  postgres:
    image: ankane/pgvector:pg15
    container_name: rag_pg
    environment:
      - POSTGRES_DB=rag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

